main: de.craftlancer.imagemaps.ImageMaps
author: SydMontague,MikaM06
version: ${project.version}
name: QuestImageMaps
commands:
  imagemap:
    permission: imagemap.admin
    description: Main command for ImageMaps
    aliases:
      - image
      - im